version: '3'

services:
  jmeter-master:
    build: ./master
    container_name: jmeter-master
    tty: true
    networks:
      - jmeter-network
  jmeter-worker:
    build: ./worker
    container_name: jmeter-worker
    networks:
      - jmeter-network

networks:
  jmeter-network:
    driver: bridge